server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reto_usuarios}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    error:
      include-stacktrace: never
appDescription: "User API"
appVersion: "1.0.0"
